import fs from 'node:fs/promises';
const debate = await fs.readFile(new URL('../worker/debate.mjs', import.meta.url), 'utf8');
const main = (await fs.readFile(new URL('../worker/index.mjs', import.meta.url), 'utf8')).replace("import { debateRoutes } from './debate.mjs';\n", '');
await fs.writeFile(new URL('../worker/deploy.js', import.meta.url), '// Generated by node scripts/build-worker.mjs. Paste this entire file into Cloudflare.\n' + debate + '\n' + main);
